include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - hash_and_equals
    - no_duplicate_case_values
    - no_leading_underscores_for_local_identifiers
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_parameters
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_relative_imports
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_constructor_name
    - unnecessary_lambdas
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - always_declare_return_types
    - prefer_const_constructors
    - avoid_void_async
    - prefer_final_locals
